### ISSUE TITLE
[Feature Request] rounded ends on the progressBar

### ISSUE THREAD

**Issue by SillyV** [owl-93/Determinate-Progress-View#2]
The progress bar ideally would have 4 variables,
Something like 

radiusInnerEnd
radiusOuterEnd
radiusInnerStart
raiusOuterStart

But even just a single radius variable, or even a Boolean for rounded ends would be good as designers are often asking for rounded ends on those.

**Comment by owl-93** [comment]
# This has been implemented in v1.2

## XML
```xml
app:strokeEndStyle="square"
app:strokeEndStyle="round"
```
## Kotlin
```kotlin
progressView.strokeEnd = Paint.Cap.ROUND
//or
progressView.strokeEnd = Paint.Cap.SQUARE
```

The default value is Round
